app/models/models.py
from flask_login import UserMixin
from werkzeug.security import (
    check_password_hash,
    generate_password_hash,
)

from app.app import db


class User(UserMixin, db.Model):

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True, nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(200), nullable=False)
    created_on = db.Column(db.DateTime, nullable=True)
    last_login = db.Column(db.DateTime, nullable=True)

    def set_password(self, password):
        """Create hashed password."""
        self.password = generate_password_hash(password, method="sha256")

    def check_password(self, password):
        """Check hashed password."""
        return check_password_hash(self.password, password)

    def __repr__(self):
        return "<User {}>".format(self.username)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    PasswordField,
    StringField,
    SubmitField,
)
from wtforms.validators import (
    DataRequired,
    Email,
    EqualTo,
    Length,
)


class RegisterForm(FlaskForm):
    username = StringField(label="Username", validators=[DataRequired()])
    email = StringField(
        "Email",
        validators=[
            Length(min=6),
            Email(message="Enter a valid email."),
            DataRequired(),
        ],
    )
    password = PasswordField(
        "Password",
        validators=[
            DataRequired(),
            Length(min=8, message="Password must be at least 8 characters long."),
        ],
    )
    confirm = PasswordField(
        "Confirm your password",
        validators=[
            DataRequired(),
            EqualTo("password", message="Passwords must match."),
        ],
    )
    submit = SubmitField("Register")


class LoginForm(FlaskForm):
    email = StringField(
        "Email", validators=[DataRequired(), Email(message="Enter a valid email.")]
    )
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Log In")

app/__init__.py
from .app import app

app/app.py
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()


def create_app():
    """Construct the core app object."""
    app = Flask(__name__)

    # Application Configuration
    app.config.from_pyfile("config.py")

    # Initialize Plugins
    db.init_app(app)
    migrate.init_app(app, db)

    # register all blueprints
    from .views import blueprints

    for bp in blueprints:
        app.register_blueprint(bp)

    login_manager.init_app(app)
    login_manager.login_view = "auth.login"

    return app


app = create_app()

app/views/__init__.py
from .auth import auth
from .main import main

blueprints = [auth, main]

app/views/auth.py
from flask import (
    Blueprint,
    flash,
    render_template,
    request,
    url_for,
)
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user,
)
from werkzeug.utils import redirect

from ..app import (
    db,
    login_manager,
)
from ..forms import (
    LoginForm,
    RegisterForm,
)
from ..models.models import User


auth = Blueprint("auth", __name__)


@login_manager.user_loader
def load_user(user):
    return User.query.get(user)


@login_manager.unauthorized_handler
def unauthorized():
    flash("You must be logged in to view that page.")
    return redirect(url_for("auth.login"))


@auth.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(password=form.password.data):
            login_user(user)
            next_page = request.args.get("next")
            return redirect(next_page or url_for("main.index"))
        else:
            flash("Invalid username/password combination")
            return redirect(url_for("auth.login"))

    return render_template("login.html", form=form)


@auth.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if not existing_user:
            user = User(username=form.username.data, email=form.email.data)
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()
            login_user(user)
            return redirect(url_for("main.index"))
        flash("A user already exists with that email address.")
    return render_template("register.html", form=form)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

app/views/main.py
from flask import (
    Blueprint,
    render_template,
)
from flask_login import login_required


main = Blueprint("main", __name__)


@main.route("/")
@login_required
def index():
    return render_template("index.html")


@main.route("/profile")
def profile():
    return render_template("profile.html")

app/templates/includes/footer.html
    <!-- partial:partials/_footer.html -->
    <footer class="footer">
      <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">
            &copy; Mushlove - Coded by <a target="_blank" rel="noopener noreferrer" href="https://d3viliz3d.github.io/">d3viliz3d</a>.
        </span>
      </div>
    </footer>
    <!-- partial -->

app/templates/includes/navigation.html
      <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
          <a class="navbar-brand brand-logo" href="/">
            <img src="/static/assets/images/logo.svg" alt="logo" /> </a>
          <a class="navbar-brand brand-logo-mini" href="/">
            <img src="/static/assets/images/logo-mini.svg" alt="logo" /> </a>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-center">
          <!--<form class="ml-auto search-form d-none d-md-block" action="#">
            <div class="form-group">
              <input type="search" class="form-control" placeholder="Search Here">
            </div>
          </form>-->
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown d-none d-xl-inline-block user-dropdown">
              <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                <img class="img-xs rounded-circle" src="/static/assets/images/faces/face8.jpg" alt="Profile image"> </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
                <div class="dropdown-header text-center">
                  <img class="img-md rounded-circle" src="/static/assets/images/faces/face8.jpg" alt="Profile image">
                  <p class="mb-1 mt-3 font-weight-semibold">
                    {{ current_user.username }}
                  </p>
                  <p class="font-weight-light text-muted mb-0">
                    {{ current_user.email }}
                  </p>
                </div>
                <a href="#" class="dropdown-item">My Profile<i class="dropdown-item-icon ti-dashboard"></i></a>
                <!--<a href="#" class="dropdown-item">Messages <span class="badge badge-pill badge-danger">2</span><i class="dropdown-item-icon ti-comment-alt"></i></a>-->
                <a href="{{ url_for('auth.logout') }}" class="dropdown-item">Sign Out<i class="dropdown-item-icon ti-power-off"></i></a>
              </div>
            </li>
          </ul>
          <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
          </button>
        </div>
      </nav>

app/templates/includes/scripts.html
<script src="/static/assets/vendors/js/vendor.bundle.base.js"></script>
<script src="/static/assets/vendors/js/vendor.bundle.addons.js"></script>
<script src="/static/assets/js/shared/off-canvas.js"></script>
<script src="/static/assets/js/shared/misc.js"></script>

app/templates/includes/sidebar.html
<nav class="sidebar sidebar-offcanvas" id="sidebar">
<ul class="nav">
  <li class="nav-item active">
    <a class="nav-link" href="/">
      <i class="menu-icon fa fa-list-alt"></i>
      <span class="menu-title">Dashboard</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
      <i class="menu-icon fa fa-spinner"></i>
      <span class="menu-title">Agar</span>
      <i class="menu-arrow"></i>
    </a>
    <div class="collapse" id="ui-basic">
      <ul class="nav flex-column sub-menu">
        <li class="nav-item">
          <a class="nav-link" href="/buttons.html">My dishes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/dropdowns.html">Recipes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/typography.html">Inventory</a>
        </li>
      </ul>
    </div>
  </li>
    <li class="nav-item">
    <a class="nav-link" href="/basic-elements.html">
      <i class="menu-icon fa fa-beer"></i>
      <span class="menu-title">Spawn</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/basic-elements.html">
      <i class="menu-icon fa fa-archive"></i>
      <span class="menu-title">Tubs</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('auth.logout') }}" >
      <i class="menu-icon fa fa-power-off"></i>
      <span class="menu-title">Logout</span>
    </a>
  </li>

</ul>
</nav>

app/templates/layouts/base-fullscreen.html
<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="/static/assets/images/favicon.png" />
    <link rel="canonical"     href="https://appseed.us/admin-dashboards/django-star-admin" />

    <title>{% block title %}{% endblock %} - Mush Love - Agar and Mushrooms Growing Community Log</title>

    <link rel="stylesheet" href="/static/assets/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/static/assets/vendors/iconfonts/ionicons/dist/css/ionicons.css">
    <link rel="stylesheet" href="/static/assets/vendors/iconfonts/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="/static/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="/static/assets/vendors/css/vendor.bundle.addons.css">

    <link rel="stylesheet" href="/static/assets/css/shared/style.css">
    <link rel="stylesheet" href="/static/assets/css/mushlove/style.css">
    <link rel="stylesheet" href="/static/assets/css/mushlove/custom.css">

    <!-- Specific CSS goes HERE -->
    {% block stylesheets %}{% endblock stylesheets %}

  </head>
  <body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">

          {% block content %}{% endblock content %}

        </div>
    </div>
    <!-- container-scroller -->

    {% include 'includes/scripts.html' %}

    <!-- Specific JS goes HERE -->
    {% block javascripts %}{% endblock javascripts %}

  </body>

</html>

app/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="/static/assets/images/favicon.png" />
    <link rel="canonical"     href="https://appseed.us/admin-dashboards/django-star-admin" />

    <title>{% block title %}{% endblock %} - Mush Love - Agar and Mushrooms Growing Community Log</title>

    <link rel="stylesheet" href="/static/assets/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/static/assets/vendors/iconfonts/ionicons/dist/css/ionicons.css">
    <link rel="stylesheet" href="/static/assets/vendors/iconfonts/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="/static/assets/vendors/iconfonts/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="/static/assets/vendors/css/vendor.bundle.addons.css">

    <link rel="stylesheet" href="/static/assets/css/shared/style.css">
    <link rel="stylesheet" href="/static/assets/css/mushlove/style.css">
    <link rel="stylesheet" href="/static/assets/css/mushlove/custom.css">

    <!-- Specific CSS goes HERE -->
    {% block stylesheets %}{% endblock stylesheets %}

  </head>
  <body>
    <div class="container-scroller">

      {% include 'includes/navigation.html' %}

      <!-- partial -->
      <div class="container-fluid page-body-wrapper">

        {% include 'includes/sidebar.html' %}

        <!-- partial -->
        <div class="main-panel">

          {% block content %}{% endblock content %}

          {% include 'includes/footer.html' %}

        </div>
        <!-- main-panel ends -->

      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->

    {% include 'includes/scripts.html' %}

    <!-- Specific JS goes HERE -->
    {% block javascripts %}{% endblock javascripts %}

  </body>
</html>

app/templates/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content-wrapper d-flex align-items-center auth auth-bg-1 theme-one">
      <div class="row w-100">
        <div class="col-lg-4 mx-auto">

          <h2 class="text-center text-white mb-4">Login</h2>
          <p class="text-center text-white">
            Add your credentials
          </p>
          <br />
          <div class="auto-form-wrapper">

            {% for message in get_flashed_messages() %}
              <div class="alert alert-warning">
                <button
                  type="button"
                  class="close"
                  data-dismiss="alert">
                    x
                  </button>
                {{ message }}
              </div>
            {% endfor %}

            <form method="POST" action="{{ url_for('auth.login') }}">
              {{ form.csrf_token }}

              <div class="form-group">
                <label class="label">{{ form.email.label.text }}</label>
                <div class="input-group">
                  {{ form.email(placeholder="example@gmail.com", class='form-control') }}
                  <div class="input-group-append">
                    <span class="input-group-text">
                      <i class="mdi mdi-check-circle-outline"></i>
                    </span>
                  </div>
                </div>
                <ul class="errors">
                  {% for error in form.email.errors %}
                    <li>{{ error }}</li>
                  {% endfor %}
                </ul>
              </div>

              <div class="form-group">
                <label class="label">{{ form.password.label.text }}</label>
                <div class="input-group">
                  {{ form.password(placeholder="********", class='form-control') }}
                  <div class="input-group-append">
                    <span class="input-group-text">
                      <i class="mdi mdi-check-circle-outline"></i>
                    </span>
                  </div>
                </div>
                <ul class="errors">
                  {% for error in form.password.errors %}
                    <li>{{ error }}</li>
                  {% endfor %}
                </ul>
              </div>

              <div class="form-group">
                {{ form.submit(class="btn btn-primary submit-btn btn-block") }}
              </div>
              <div class="form-group d-flex justify-content-between">
                <div class="form-check form-check-flat mt-0">
                  <label class="form-check-label">
                    <input type="checkbox" class="form-check-input" checked> Keep me signed in </label>
                </div>
                <a href="#" class="text-small forgot-password text-black">Forgot Password</a>
              </div>
              <!--<div class="form-group">
                <button class="btn btn-block g-login">
                  <img class="mr-3" src="/static/assets/images/file-icons/icon-google.svg" alt="">Log in with Google</button>
              </div>-->
              <div class="text-block text-center my-3">
                <span class="text-small font-weight-semibold">Not a member?</span>
                <a href="{{ url_for('auth.register') }}" class="text-black text-small">Create new account</a>
              </div>
            </form>
          </div>

        </div>
      </div>
    </div>

{% endblock content %}

app/templates/page-403.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} 403 Error {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
        <div class="row flex-grow">
            <div class="col-lg-7 mx-auto text-white">
                <div class="row align-items-center d-flex flex-row">
                    <div class="col-lg-6 text-lg-right pr-lg-4">
                        <h1 class="display-1 mb-0">403</h1>
                    </div>
                    <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
                        <h2>SORRY!</h2>
                        <h3 class="font-weight-light">Access denied - please authenticate.</h3>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-12 text-center mt-xl-2">
                        <a class="text-white font-weight-medium" href="/login.html" >Login</a>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-12 mt-xl-2">
                        <p class="footer-text text-white text-center">
                        &copy; <a class="text-white" href="https://www.bootstrapdash.com/?ref=23" target="_blank">BootstrapDash</a> 
                        - Coded by <a class="text-white" href="https://appseed.us" target="_blank">AppSeed</a>
                        </p> 
                    </div>
                </div>
            </div>
        </div>        
    </div>
    <!-- content-wrapper ends -->

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

app/templates/page-404.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} 404 Error {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
    <div class="row flex-grow">
      <div class="col-lg-7 mx-auto text-white">
        <div class="row align-items-center d-flex flex-row">
          <div class="col-lg-6 text-lg-right pr-lg-4">
            <h1 class="display-1 mb-0">404</h1>
          </div>
          <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
            <h2>SORRY!</h2>
            <h3 class="font-weight-light">The page you’re looking for was not found.</h3>
          </div>
        </div>
        <div class="row mt-5">
          <div class="col-12 text-center mt-xl-2">
            <a class="text-white font-weight-medium" href="/">Back to HOME</a>
          </div>
        </div>
        <div class="row mt-5">
          <div class="col-12 mt-xl-2">
            <p class="footer-text text-white text-center">
              &copy; <a class="text-white" href="https://www.bootstrapdash.com/?ref=23" target="_blank">BootstrapDash</a> 
              - Coded by <a class="text-white" href="https://appseed.us" target="_blank">AppSeed</a>
            </p>          
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

app/templates/page-500.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} 404 Error {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content-wrapper d-flex align-items-center text-center error-page bg-info">
      <div class="row flex-grow">
        <div class="col-lg-7 mx-auto text-white">
          <div class="row align-items-center d-flex flex-row">
            <div class="col-lg-6 text-lg-right pr-lg-4">
              <h1 class="display-1 mb-0">500</h1>
            </div>
            <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
              <h2>SORRY!</h2>
              <h3 class="font-weight-light">Internal server error!</h3>
            </div>
          </div>
          <div class="row mt-5">
            <div class="col-12 text-center mt-xl-2">
              <a class="text-white font-weight-medium" href="/">Back to HOME</a>
            </div>
          </div>
          <div class="row mt-5">
            <div class="col-12 mt-xl-2">
              <p class="footer-text text-white text-center">
                &copy; <a class="text-white" href="https://www.bootstrapdash.com/?ref=23" target="_blank">BootstrapDash</a> 
                - Coded by <a class="text-white" href="https://appseed.us" target="_blank">AppSeed</a>
              </p>               
            </div>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

app/templates/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %}Register{% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="content-wrapper d-flex align-items-center auth register-bg-1 theme-one">
    <div class="row w-100">
      <div class="col-lg-4 mx-auto">
        <h2 class="text-center mb-4">Register</h2>
        <p class="text-center">
          Add your credentials
        </p>
        <br />

        <div class="auto-form-wrapper">

          {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
              <button
                type="button"
                class="close"
                data-dismiss="alert">
                x
              </button>
              {{ message }}
            </div>
          {% endfor %}

          <form method="POST" action="{{ url_for('auth.register') }}">
            {{ form.csrf_token }}

            <div class="form-group">
              <label class="label">{{ form.username.label.text }}</label>
              <div class="input-group">
                {{ form.username(placeholder="username", class='form-control') }}
                <div class="input-group-append">
                  <span class="input-group-text">
                    <i class="mdi mdi-check-circle-outline"></i>
                  </span>
                </div>
              </div>
              <ul class="errors">
                {% for error in form.username.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            </div>

            <div class="form-group">
              <label class="label">{{ form.email.label.text }}</label>
              <div class="input-group">
                {{ form.email(placeholder="example@gmail.com", class='form-control') }}
                <div class="input-group-append">
                  <span class="input-group-text">
                    <i class="mdi mdi-check-circle-outline"></i>
                  </span>
                </div>
              </div>
              <ul class="errors">
                {% for error in form.email.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            </div>

            <div class="form-group">
              <label class="label">{{ form.password.label.text }}</label>
              <div class="input-group">
                {{ form.password(placeholder="********", class='form-control') }}
                <div class="input-group-append">
                  <span class="input-group-text">
                    <i class="mdi mdi-check-circle-outline"></i>
                  </span>
                </div>
              </div>
              <ul class="errors">
                {% for error in form.password.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
            <div class="form-group">
              <label class="label">{{ form.confirm.label.text }}</label>
              <div class="input-group">
                {{ form.confirm(placeholder="********", class='form-control') }}
                <div class="input-group-append">
                  <span class="input-group-text">
                    <i class="mdi mdi-check-circle-outline"></i>
                  </span>
                </div>
              </div>
              <ul class="errors">
                {% for error in form.confirm.errors %}
                  <li>{{ error }}</li>
                {% endfor %}
              </ul>
            </div>
            <!--<div class="form-group d-flex justify-content-center">
              <div class="form-check form-check-flat mt-0">
                <label class="form-check-label">
                  <input type="checkbox" class="form-check-input" checked>I agree to the terms</label>
              </div>
            </div>-->
            <div class="form-group">
              {{ form.submit(class="btn btn-primary submit-btn btn-block") }}
            </div>
            <div class="text-block text-center my-3">
              <span class="text-small font-weight-semibold">Already have and account?</span>
              <a href="{{ url_for('auth.login') }}" class="text-black text-small">Login</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}